with-expecter: true
issue-845-fix: true
disable-version-string: true
resolve-type-alias: false
packages:
    github.com/raythx98/url-shortener/repositories:
        interfaces:
            IRepository:
    github.com/raythx98/url-shortener/service:
        interfaces:
            ConfigProvider:
    github.com/raythx98/url-shortener/tools/crypto:
        interfaces:
            ICrypto:
    github.com/raythx98/url-shortener/tools/random:
        interfaces:
            IRandom: