// Code generated by mockery. DO NOT EDIT.

package qrcode

import mock "github.com/stretchr/testify/mock"

// MockIQrCode is an autogenerated mock type for the IQrCode type
type MockIQrCode struct {
	mock.Mock
}

type MockIQrCode_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIQrCode) EXPECT() *MockIQrCode_Expecter {
	return &MockIQrCode_Expecter{mock: &_m.Mock}
}

// Encode provides a mock function with given fields: content
func (_m *MockIQrCode) Encode(content string) ([]byte, error) {
	ret := _m.Called(content)

	if len(ret) == 0 {
		panic("no return value specified for Encode")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(content)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(content)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(content)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIQrCode_Encode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encode'
type MockIQrCode_Encode_Call struct {
	*mock.Call
}

// Encode is a helper method to define mock.On call
//   - content string
func (_e *MockIQrCode_Expecter) Encode(content interface{}) *MockIQrCode_Encode_Call {
	return &MockIQrCode_Encode_Call{Call: _e.mock.On("Encode", content)}
}

func (_c *MockIQrCode_Encode_Call) Run(run func(content string)) *MockIQrCode_Encode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIQrCode_Encode_Call) Return(_a0 []byte, _a1 error) *MockIQrCode_Encode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIQrCode_Encode_Call) RunAndReturn(run func(string) ([]byte, error)) *MockIQrCode_Encode_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIQrCode creates a new instance of MockIQrCode. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIQrCode(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIQrCode {
	mock := &MockIQrCode{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
