// Code generated by mockery. DO NOT EDIT.

package crypto

import mock "github.com/stretchr/testify/mock"

// MockICrypto is an autogenerated mock type for the ICrypto type
type MockICrypto struct {
	mock.Mock
}

type MockICrypto_Expecter struct {
	mock *mock.Mock
}

func (_m *MockICrypto) EXPECT() *MockICrypto_Expecter {
	return &MockICrypto_Expecter{mock: &_m.Mock}
}

// ComparePasswordAndHash provides a mock function with given fields: password, encodedHash
func (_m *MockICrypto) ComparePasswordAndHash(password string, encodedHash string) (bool, error) {
	ret := _m.Called(password, encodedHash)

	if len(ret) == 0 {
		panic("no return value specified for ComparePasswordAndHash")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return rf(password, encodedHash)
	}
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(password, encodedHash)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(password, encodedHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockICrypto_ComparePasswordAndHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ComparePasswordAndHash'
type MockICrypto_ComparePasswordAndHash_Call struct {
	*mock.Call
}

// ComparePasswordAndHash is a helper method to define mock.On call
//   - password string
//   - encodedHash string
func (_e *MockICrypto_Expecter) ComparePasswordAndHash(password interface{}, encodedHash interface{}) *MockICrypto_ComparePasswordAndHash_Call {
	return &MockICrypto_ComparePasswordAndHash_Call{Call: _e.mock.On("ComparePasswordAndHash", password, encodedHash)}
}

func (_c *MockICrypto_ComparePasswordAndHash_Call) Run(run func(password string, encodedHash string)) *MockICrypto_ComparePasswordAndHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockICrypto_ComparePasswordAndHash_Call) Return(match bool, err error) *MockICrypto_ComparePasswordAndHash_Call {
	_c.Call.Return(match, err)
	return _c
}

func (_c *MockICrypto_ComparePasswordAndHash_Call) RunAndReturn(run func(string, string) (bool, error)) *MockICrypto_ComparePasswordAndHash_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateFromPassword provides a mock function with given fields: password
func (_m *MockICrypto) GenerateFromPassword(password string) (string, error) {
	ret := _m.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for GenerateFromPassword")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(password)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockICrypto_GenerateFromPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateFromPassword'
type MockICrypto_GenerateFromPassword_Call struct {
	*mock.Call
}

// GenerateFromPassword is a helper method to define mock.On call
//   - password string
func (_e *MockICrypto_Expecter) GenerateFromPassword(password interface{}) *MockICrypto_GenerateFromPassword_Call {
	return &MockICrypto_GenerateFromPassword_Call{Call: _e.mock.On("GenerateFromPassword", password)}
}

func (_c *MockICrypto_GenerateFromPassword_Call) Run(run func(password string)) *MockICrypto_GenerateFromPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockICrypto_GenerateFromPassword_Call) Return(encodedHash string, err error) *MockICrypto_GenerateFromPassword_Call {
	_c.Call.Return(encodedHash, err)
	return _c
}

func (_c *MockICrypto_GenerateFromPassword_Call) RunAndReturn(run func(string) (string, error)) *MockICrypto_GenerateFromPassword_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockICrypto creates a new instance of MockICrypto. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockICrypto(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockICrypto {
	mock := &MockICrypto{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
