basePath: /api/v1
host: localhost:5051
info:
  contact:
    email: raythx98@gmail.com
    name: Ray Toh
    url: https://www.raythx.com
  title: URL Shortener Server
  version: "1.0"
paths: {}
swagger: "2.0"
